#!/bin/sh
PATH="/usr/local/bin:$PATH"
. $HOME/.nvm/nvm.sh
nvm use 6

#
# Ensure the repository passes WordPress coding standards.
#
PHPFILES=$(git diff --cached --name-only --diff-filter=AM | grep '.php' | tr '\n' ' ')
if [[ $PHPFILES ]]
then
	vendor/bin/phpcs --standard=WordPress --report=source $PHPFILES
	vendor/bin/phpcs --standard=WordPress $PHPFILES
fi

#
# Ensure the repository passes Grunt lint tasks
#
SASS=$(git diff --cached --name-only --diff-filter=AM | grep '.scss' | tr '\n' ' ')
node_modules/sass-lint/bin/sass-lint.js -c .sass-lint.yml '$SASS'
grunt sasslint

if [ $PHPFILES ] && [[ $(vendor/bin/phpcs -q --standard=WordPress --report=source $PHPFILES) ]]
then
	echo "Fix all issues before commit."
	exit 1
fi

SASSLINT=$(grunt sasslint)
if echo "$SASSLINT" | grep -q "error"; then
	echo "Fix the error before commit."
	exit 1
fi

exit 0
