#!/bin/sh
#
# Ensure the repository passes WordPress coding standards.
#
vendor/bin/phpcs --standard=WordPress --report=source ./*.php ./src
vendor/bin/phpcs --standard=WordPress ./*.php ./src
if [[ $(vendor/bin/phpcs -q --standard=WordPress --report=source ./*.php ./src) ]]
then
	echo "Fix the error before commit."
	exit 1
fi
